# Generated by Django 4.2.5 on 2024-05-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_category_movie_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
