# Generated by Django 5.0.4 on 2024-04-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Untitled Movie', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default_poster.jpg', upload_to='posters/'),
        ),
    ]
